redirect_uris = "http://localhost:8501/"
testing_mode = true
GOOGLE_CLIENT_ID = 'client_id'
GOOGLE_CLIENT_SECRET = 'client_secret'
redirect_url_test = 'http://localhost:8501/'
redirect_url = "https://your_app_url..."