redirect_uris = "http://localhost:8501/"
testing_mode = true
client_id = '1071879158631-e9d2jlfng4ja5ovrueabr2vbhk39mmip.apps.googleusercontent.com'
client_secret = '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'
redirect_url_test = 'http://localhost:8501/'
redirect_url = "https://your_app_url..."